# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ingres/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ingres)

endif


# Define the compressed file
COMPRESSED_FILE := vendor/xiaomi/ingres/proprietary/vendor/lib64/libxmi_high_dynamic_range_cdsp.so.xz

ifneq (,$(wildcard $(COMPRESSED_FILE)))

# Define the target directory
TARGET_DIR := vendor/xiaomi/ingres/proprietary/vendor/lib64

# Rule to decompress the file
define decompress-file
    $(shell unxz -k -f $(COMPRESSED_FILE))
endef

$(call decompress-file)

$(shell cp $(COMPRESSED_FILE:.xz=) $(TARGET_DIR)/)
$(shell rm $(COMPRESSED_FILE:.xz=))

endif
